Badly placed ()'s.
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "marginalization.py", line 34, in <module>
    np.random.seed(args.seed)
NameError: name 'args' is not defined
